"""add unique active slot index

Revision ID: a35fad24c048
Revises: adf35cf2c8d5
Create Date: 2026-08-24 10:54:41.874254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35fad24c048'
down_revision: Union[str, Sequence[str], None] = 'adf35cf2c8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_active_slot', 'bookings', ['booking_date', 'booking_time'], unique=True, sqlite_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_active_slot', table_name='bookings', sqlite_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###
