"""Initial migration

Revision ID: adf35cf2c8d5
Revises: 
Create Date: 2026-08-24 00:44:46.736706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf35cf2c8d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.Time(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', name='bookingstatus'), nullable=False,
              server_default='active'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index('ix_bookings_booking_date', 'bookings', ['booking_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_booking_date', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
